### ISSUE TITLE
Please update for 1.20 when possible

### ISSUE THREAD

**Issue by eggbeatre** [RMJTromp/ChatEmojis#14]
**Describe the bug**
ChatEmojis cannot be enabled on a 1.20 server

**To Reproduce**
1. load server
2. attempt to run a command

**Screenshots**
![Capture](https://github.com/RMJTromp/ChatEmojis/assets/130617475/e537d3a7-c7de-44b3-9022-df26f3254e97)

**Server Jar & Version:**
 - Jar: **Paper**
 - Version: **1.20**
  
 thanks!

**Comment by RMJTromp** [comment]
Hi @eggbeatre, considering you probably use this plugin more than I do, and more than I ever will, could you please install this jar file and test it to see if everything is working as it previously was? The complete changelog (i think) can be found here #15 
[ChatEmojis-2.3.3.zip](https://github.com/RMJTromp/ChatEmojis/files/11754095/ChatEmojis-2.3.3.zip)

Could you please get back to me with a conclusion, ty in advance

**Comment by RainbowTea** [comment]
> Hi @eggbeatre, considering you probably use this plugin more than I do, and more than I ever will, could you please install this jar file and test it to see if everything is working as it previously was? The complete changelog (i think) can be found here #15
> 
> [ChatEmojis-2.3.3.zip](https://github.com/RMJTromp/ChatEmojis/files/11754095/ChatEmojis-2.3.3.zip)
> 
> Could you please get back to me with a conclusion, ty in advance

I ran this version for 2 days, seems like it works fine.

**Comment by FezzyDev** [comment]
I have been running this version for a few days as well, and have not run into any issues so far.
